# Site Settings
locale                   : "en-US"
title                    : "Danielle Lindsay"
title_separator          : "-"
name                     : &name "Danielle Lindsay"
description              : &description "Academic Profile"
url                      : "https://dani-lindsay.github.io"
baseurl                  : ""
repository               : "Dani-Lindsay/Dani-Lindsay.github.io"

# Theme Settings
remote_theme             : "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "default"
masthead_title          : " "
search                  : false

# Site navigation
atom_feed:
  hide                   : true

# Site Author
author:
  name             : "Danielle Lindsay"
  avatar           : "profile.jpeg"
  bio              : "PhD Researcher at UC Berkeley"
  location         : "Berkeley, California"
  employer         : "University of California, Berkeley"
  email            : "danielle.lindsay@berkeley.edu"
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-redirect-from
